![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


In [11]:
print(sorted(my_array[:3],reverse=True))

[2, 1, 0]


In [12]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [16]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [22]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [25]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [26]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [29]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [32]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [34]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [35]:
x == "Loro"

array([ True, False, False,  True, False])

In [38]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [45]:
print(np.where(x == "Loro")[0])

[0 3]


In [41]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [48]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [49]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [53]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [54]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

8
80


In [57]:
print(x.dtype)

float64


In [58]:
x = np.full(10, 0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [59]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

4
40


In [60]:
print(x.dtype)

int32


In [61]:
x = np.full(10, 0, dtype=np.int8)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [62]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

1
10


In [73]:
2 ** 8

256

In [ ]:
# 101010110

In [83]:
2**0 + 2**1 + 2**2 + 2**3 + 2**4 + 2**5 + 2**6 + 2**7

255

In [ ]:
[-128,127]

In [79]:
x[3] = 1
# x[3] = 127
# x[3] = 128
print(x)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [84]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [85]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [87]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [96]:
type(np.where(ejer_12 != 0)[0])

numpy.ndarray

In [99]:
ejer_12[np.where(ejer_12 != 0)]

array([1, 2, 4])

In [100]:
def f_ejer_12(array_1d):
    return np.where(array_1d != 0)[0]

In [105]:
arr_ej = np.array([3,7,2,0,5,0])
print(f_ejer_12(arr_ej))
print(arr_ej[f_ejer_12(arr_ej)])

[0 1 2 4]
[3 7 2 5]


In [107]:
np.nonzero(ejer_12)[0]

array([0, 1, 4], dtype=int64)

In [115]:
np.argwhere(ejer_12).reshape(len(np.argwhere(ejer_12)))

array([0, 1, 4], dtype=int64)

In [118]:
np.hstack(np.argwhere(ejer_12))

array([0, 1, 4], dtype=int64)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [204]:
x = np.random.randint(100, size=(10,10))
print(x)
print("Minimo", np.min(x), x.min())
print("Máximo", np.max(x), x.max())
print("Sumatorio", np.sum(x), x.sum())
print("Media", np.mean(x), x.mean())
print("Mediana", np.median(x))

[[25 70 34 26 63 96 25 48 51 93]
 [99  1 54 17 79 22 99 83 66 40]
 [24  7 57  2 60 27  1 26 64 41]
 [96  2 91  1  4 91 14 83 85 63]
 [ 5 69 71 69 37 49  4 53 96 82]
 [83 64 10 39 81 38 96 52 63 72]
 [13 41  3 39 22 50 31 86 26 63]
 [ 1  6 79 65 48  6 58  9 19 62]
 [27  3 24 91 85 15 99 44 37  8]
 [86 53 20 96 91 46 64 53  4 70]]
Minimo 1 1
Máximo 99 99
Sumatorio 4806 4806
Media 48.06 48.06
Mediana 49.5


In [214]:
# ej = np.array([1000, 1000, 1100, 1100, 9000])
# print(ej.mean())
# print(np.median(ej))

2640.0
1100.0


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [24]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.91873788 0.21277298 0.9275536  0.13118274 0.07343957 0.30141392
 0.68681007 0.49814433 0.32439506 0.02748898 0.81015484 0.35291282
 0.15635772 0.19180401 0.16761322 0.52085193 0.99878367 0.8718723
 0.83912035 0.32041493 0.99602323 0.09405084 0.33584508 0.59227142
 0.75602511 0.94406194 0.67440189 0.94659437 0.88548991 0.57790311]
0.5378163935382165


In [25]:
print(x.sum()/len(x))

0.5378163935382165


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [28]:
ejer_15 = np.full((10,10), 1)
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [29]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [30]:
def f_ejer_15(tamaño):
    matrix = np.full(tamaño, 1)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [32]:
print(f_ejer_15((3,3)))

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [33]:
print(f_ejer_15((8,8)))

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [34]:
print(f_ejer_15((2,2)))

[[1 1]
 [1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [37]:
x = np.zeros((8,8), dtype=np.int16)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [39]:
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [40]:
a = np.array([[0,1],
              [1,0]])
print(a)

[[0 1]
 [1 0]]


In [41]:
x = np.tile(a, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [42]:
x = np.random.randint(1,20, (5,5))
print(x)

[[ 2 18 18 15  4]
 [14  7 12  6  6]
 [14 14  2 16  9]
 [13 18  4  3 15]
 [14  2 16  4  6]]


In [44]:
np.mean(x)

10.08

In [46]:
(x - np.mean(x)) / np.std(x) 

array([[-1.43028789,  1.40196536,  1.40196536,  0.87091787, -1.07625624],
       [ 0.69390205, -0.54520875,  0.33987039, -0.72222458, -0.72222458],
       [ 0.69390205,  0.69390205, -1.43028789,  1.0479337 , -0.19117709],
       [ 0.51688622,  1.40196536, -1.07625624, -1.25327206,  0.87091787],
       [ 0.69390205, -1.43028789,  1.0479337 , -1.07625624, -0.72222458]])

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [47]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [50]:
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [63]:
z = x.copy()
z[(z >= 3) & (z <= 8)] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [57]:
n = 0
for i in range(5):
    # n = n + 1
    n += 1
    print(n)

1
2
3
4
5


In [61]:
n = 1
for i in range(5):
    # n = n * 2
    n *= 2
    print(n)

2
4
8
16
32
